name: Compilar Lampiao CS4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Preparar projeto
        run: |
          unzip -q lampiao-cs4-do-zero.zip
          cd lampiao-cs4
          chmod +x gradlew
          ./gradlew build --no-daemon

      - name: Gerar download
        uses: actions/upload-artifact@v4
        with:
          name: lampiao-cs4
          path: lampiao-cs4/build/libs/*.jar
